### ISSUE TITLE
Get the png image from roi file

### ISSUE THREAD

**Issue by cao1124** [Holliemin9090/Mammographic-mass-CAD-via-pseudo-color-mammogram-and-Mask-R-CNN#1]
How did you get the input png image for preprocessing through the roi file？I download OsiriX Lite software，which can display dcm images and roi annotations on it，but I cannot convert the roi file to a mask png image.

Look forward to your reply.

**Comment by Holliemin9090** [comment]
Sorry for the late reply. We actually received the data already in PNG format from a collaborator. But I think the image and annotation data can be opened and saved into another format in MATLAB and Python. I found this webpage which might turn out to be helpful to you. https://www.researchgate.net/post/How_do_I_use_contour_points_in_INBreast_database

**Comment by cao1124** [comment]
> Sorry for the late reply. We actually received the data already in PNG format from a collaborator. But I think the image and annotation data can be opened and saved into another format in MATLAB and Python. I found this webpage which might turn out to be helpful to you. https://www.researchgate.net/post/How_do_I_use_contour_points_in_INBreast_database

**Comment by cao1124** [comment]
> Sorry for the late reply. We actually received the data already in PNG format from a collaborator. But I think the image and annotation data can be opened and saved into another format in MATLAB and Python. I found this webpage which might turn out to be helpful to you. https://www.researchgate.net/post/How_do_I_use_contour_points_in_INBreast_database

**Comment by cao1124** [comment]
very thanks for your reply,
I have another question, how do you handle the detection of discrete、tiny calcification points in your project？

**Comment by Holliemin9090** [comment]
This application is designed for breast mass detection. It does not detect calcifications at this stage unfortunately...
