### ISSUE TITLE
FileNotFoundError: [WinError 3] 

### ISSUE THREAD

**Issue by latoa** [Holliemin9090/Mammographic-mass-CAD-via-pseudo-color-mammogram-and-Mask-R-CNN#5]
Traceback (most recent call last):
  File "mamo_CAD.py", line 346, in <module>
    train(model)
  File "mamo_CAD.py", line 182, in train
    dataset_train.load_mamogram(r'\train')
  File "mamo_CAD.py", line 113, in load_mamogram
    files = os.listdir(ROOT_DIR + MAMOGRAM_IMAGE_DIR + subset + "\\")
FileNotFoundError: [WinError 3] O sistema não conseguiu localizar o caminho especificado:

**Comment by Holliemin9090** [comment]
files = os.listdir(ROOT_DIR + MAMOGRAM_IMAGE_DIR + subset + "\")
Please specify your own directory of images here.

**Comment by latoa** [comment]
thanks
