### ISSUE TITLE
Are you using all the  410 images of the dataset?

### ISSUE THREAD

**Issue by latoa** [Holliemin9090/Mammographic-mass-CAD-via-pseudo-color-mammogram-and-Mask-R-CNN#6]

**Comment by Holliemin9090** [comment]
Yes. The whole dataset was split into 60% for training, 20% for validation and 20% for testing.

**Comment by latoa** [comment]
I have this results after the first trainning:
Sensitivity:0.63636
False positive per image:0.32308
Dice:0.88455@0.0592

**Comment by Holliemin9090** [comment]
There is a parameter DETECTION_MIN_CONFIDENCE in the mamo_CAD.py file which is the confidence threshold for detection. If you set this parameter lower, the sensitivity would normally increase but also with a higher false positive rate.
