### ISSUE TITLE
convert .roi/ .xml file to png(mask) 

### ISSUE THREAD

**Issue by jasminjahanpuspo** [Holliemin9090/Mammographic-mass-CAD-via-pseudo-color-mammogram-and-Mask-R-CNN#8]
Hello, @Holliemin9090  your work is very well structured. As I am a beginner I understand this easily.
I am using Inbreast datasets. Here I can not convert the .xml file to png format to find the ground truth values. 
1)I used code https://gist.github.com/jendelel/3a8e768a8eb9345d49f2a82d02946122 to process xml files for raw annotation images. But got all values zeros. Also, this code is written for files, not folders. 
2) I used code (https://www.mathworks.com/matlabcentral/fileexchange/7868-use-mac-os-x-xml-plists-with-matlab) to convert .xml file png format. But I got stuck.
3) here i got your code on (https://gist.github.com/Holliemin9090/52d1d5b953cd0f4df331628f0022ab88) when run code on colab i got all values zeros. 
4)  Also, OsiriX Lite software is only for dicom files not for .xml/.roi  file.
5) Is there any other way to extract the .xml file to png file?
6) or to extract from .roi to png file?
Any kind of help will be appreciated

**Comment by jasminjahanpuspo** [comment]
Hello, I used https://github.com/wentaozhu/inbreast code to get the mass(in .png format) image from the .xml file.

**Comment by Holliemin9090** [comment]
Hi, I think this github page should be helpful.
https://gist.github.com/jendelel/3a8e768a8eb9345d49f2a82d02946122

Cheers.

**Comment by Holliemin9090** [comment]
Hi,
Sorry, I just saw your message. Glad you have solved the problem. Personally I find the code in https://gist.github.com/jendelel/3a8e768a8eb9345d49f2a82d02946122  helpful. Here is an example of the groundtruth mask I extracted using this code. 
![image](https://user-images.githubusercontent.com/28077988/113810756-3e48e380-97ae-11eb-9d65-875b3b78759b.png)

Cheers.

**Comment by jasminjahanpuspo** [comment]
Yes, I also tried this somehow I got all values zeros. Here,is an screenshot ![Screenshot_2021-04-07-12-50-03-36.png](https://user-images.githubusercontent.com/51731547/113823364-63365a00-97a0-11eb-9025-124c252d07bc.png)

**Comment by jasminjahanpuspo** [comment]
@Holliemin9090 
Sorry for disturbing you again. In your paper[1] mentioned that images are trained with gray images and also compared with pseudo color images. 
1) As far I tried very hard to train my images with gray images I succeed but when I failed to segment the images. I through that I made mistake to train my images if that's possible could you help me? Also, I check GitHub matterport mask rcnn they discussed that segmentation in gray images could not possible.
2) After trained pseudo color masks are generated (4028,3328,3) But when i checked it shows (4028,3328,4). 


[1] Fully Automatic Computer-aided Mass Detection and Segmentation via Pseudo-color Mammograms and Mask R-CNN
Thanks in advance.

**Comment by Holliemin9090** [comment]
Hi, sorry for the late reply. When training on grayscale image, I used a 3 channel gray image by repeating the 1-channel grayscale image in 3 channels. 
As for the 4 channel issue, I am not sure what could cause this issue. I didn't experience this problem.
